export const data = [
  {
    id: "169881",
    name: "Domino's Pizza",
    cloudinaryImageId:
      "RX_THUMBNAIL/IMAGES/VENDOR/2024/10/24/26e7c445-bbbe-42f0-b185-1666cdf9f9da_169881.JPG",
    locality: "Palakkad",
    areaName: "Vidyut Nagar",
    costForTwo: "₹400 for two",
    cuisines: ["Pizzas", "Italian", "Pastas", "Desserts"],
    avgRating: 4.3,
    parentId: "2456",
    avgRatingString: "4.3",
    totalRatingsString: "1.9K+",
    sla: {
      deliveryTime: 25,
      lastMileTravel: 2.1,
      serviceability: "SERVICEABLE",
      slaString: "20-25 mins",
      lastMileTravelString: "2.1 km",
      iconType: "ICON_TYPE_EMPTY",
    },
  },
  {
    id: "336912",
    name: "Pizza Hut",
    cloudinaryImageId:
      "RX_THUMBNAIL/IMAGES/VENDOR/2024/7/17/5825f6bc-7734-4670-b72a-3731db6edb62_336912.jpg",
    locality: "Selvapalayam",
    areaName: "Vidyut Nagar",
    costForTwo: "₹350 for two",
    cuisines: ["Pizzas"],
    avgRating: 4.2,
    parentId: "721",
    avgRatingString: "4.2",
    totalRatingsString: "3.4K+",
    sla: {
      deliveryTime: 31,
      lastMileTravel: 2.3,
      serviceability: "SERVICEABLE",
      slaString: "30-35 mins",
      lastMileTravelString: "2.3 km",
      iconType: "ICON_TYPE_EMPTY",
    },
  },
  {
    id: "328821",
    name: "KFC",
    cloudinaryImageId:
      "RX_THUMBNAIL/IMAGES/VENDOR/2024/11/5/d016bb44-536a-46d6-b128-2f99f899365d_328821.JPG",
    locality: "Kajas",
    areaName: "Vidyut Nagar",
    costForTwo: "₹400 for two",
    cuisines: ["Burgers", "Fast Food", "Rolls & Wraps"],
    avgRating: 4.4,
    parentId: "547",
    avgRatingString: "4.4",
    totalRatingsString: "7.3K+",
    sla: {
      deliveryTime: 27,
      lastMileTravel: 2.2,
      serviceability: "SERVICEABLE",
      slaString: "25-30 mins",
      lastMileTravelString: "2.2 km",
      iconType: "ICON_TYPE_EMPTY",
    },
  },
  {
    id: "544117",
    name: "Nalanda Grill",
    cloudinaryImageId: "10e47ca50f6b4106d398818aaf4f5a73",
    locality: "Head Post Office",
    areaName: "Sultanpet",
    costForTwo: "₹300 for two",
    cuisines: [
      "Arabian",
      "South Indian",
      "Biryani",
      "Chinese",
      "Grill",
      "Beverages",
    ],
    avgRating: 4.3,
    parentId: "326982",
    avgRatingString: "4.3",
    totalRatingsString: "6.0K+",
    sla: {
      deliveryTime: 30,
      lastMileTravel: 1.8,
      serviceability: "SERVICEABLE",
      slaString: "30-35 mins",
      lastMileTravelString: "1.8 km",
      iconType: "ICON_TYPE_EMPTY",
    },
  },
  {
    id: "244331",
    name: "Hasi's Kitchen",
    cloudinaryImageId: "lwrgtjvcogz6ebo3s9bl",
    locality: "PC Tower",
    areaName: "Tharekkad",
    costForTwo: "₹300 for two",
    cuisines: [
      "Biryani",
      "South Indian",
      "Arabian",
      "Chinese",
      "Grill",
      "Fast Food",
    ],
    avgRating: 4.4,
    parentId: "94368",
    avgRatingString: "4.4",
    totalRatingsString: "5.3K+",
    sla: {
      deliveryTime: 32,
      lastMileTravel: 1.5,
      serviceability: "SERVICEABLE",
      slaString: "30-35 mins",
      lastMileTravelString: "1.5 km",
      iconType: "ICON_TYPE_EMPTY",
    },
  },
  {
    id: "250170",
    name: "OMR Biriyani Factory",
    cloudinaryImageId: "w7kawzfwmlcf4pblujex",
    locality: "Manjakulam Road",
    areaName: "Valakkad",
    costForTwo: "₹300 for two",
    cuisines: [
      "Biryani",
      "South Indian",
      "Arabian",
      "Chinese",
      "Grill",
      "Fast Food",
    ],
    avgRating: 4.3,
    parentId: "152100",
    avgRatingString: "4.3",
    totalRatingsString: "10K+",
    sla: {
      deliveryTime: 21,
      lastMileTravel: 0.2,
      serviceability: "SERVICEABLE",
      slaString: "20-25 mins",
      lastMileTravelString: "0.2 km",
      iconType: "ICON_TYPE_EMPTY",
    },
  },
  {
    id: "376520",
    name: "Social Kitchen - Taste of Udupi",
    cloudinaryImageId:
      "RX_THUMBNAIL/IMAGES/VENDOR/2024/7/2/98febc2c-740d-435f-81f1-bf4fbea5ca9e_376520.jpg",
    locality: "Vinayaka Colony",
    areaName: "Pallippuram",
    costForTwo: "₹150 for two",
    cuisines: [
      "South Indian",
      "North Indian",
      "Kerala",
      "Indian",
      "Beverages",
      "Snacks",
    ],
    avgRating: 4.5,
    veg: true,
    parentId: "559056",
    avgRatingString: "4.5",
    totalRatingsString: "5.2K+",
    sla: {
      deliveryTime: 36,
      lastMileTravel: 2.2,
      serviceability: "SERVICEABLE",
      slaString: "35-40 mins",
      lastMileTravelString: "2.2 km",
      iconType: "ICON_TYPE_EMPTY",
    },
  },
  {
    id: "284174",
    name: "Hotel Sri Ashok Bhavan",
    cloudinaryImageId: "lcuqpu4x67sbf5prbqcg",
    locality: "Sultanpet",
    areaName: "Vidyut Nagar",
    costForTwo: "₹300 for two",
    cuisines: ["South Indian", "Indian", "Kerala", "Beverages", "Snacks"],
    avgRating: 4.5,
    veg: true,
    parentId: "102618",
    avgRatingString: "4.5",
    totalRatingsString: "8.5K+",
    sla: {
      deliveryTime: 32,
      lastMileTravel: 1.8,
      serviceability: "SERVICEABLE",
      slaString: "30-35 mins",
      lastMileTravelString: "1.8 km",
      iconType: "ICON_TYPE_EMPTY",
    },
  },
]

export const mockData = {
  id: "284174",
  name: "Hotel Sri Ashok Bhavan",
  cloudinaryImageId: "lcuqpu4x67sbf5prbqcg",
  locality: "Sultanpet",
  areaName: "Vidyut Nagar",
  costForTwo: "₹300 for two",
  cuisines: ["South Indian", "Indian", "Kerala", "Beverages", "Snacks"],
  avgRating: 4.5,
  veg: true,
  parentId: "102618",
  avgRatingString: "4.5",
  totalRatingsString: "8.5K+",
  sla: {
    deliveryTime: 32,
    lastMileTravel: 1.8,
    serviceability: "SERVICEABLE",
    slaString: "30-35 mins",
    lastMileTravelString: "1.8 km",
    iconType: "ICON_TYPE_EMPTY",
  },
}